### PR TITLE
Add automatic toml loading

### PR DESCRIPTION
**Pull request by Giulio2002**

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]
- `init` is likely bad for it - because then all tests will also go to internet 
- need make `branch` configurable (or base-url configurable - with branch name in it)
- need some way/flag/env to disable it (maybe `dbg.EnvString` for MVP)
- this feels very easy to set empty value (on some http codes, or other corner cases) - probably need protection from empty set
```
 err == nil {
	BorMainnet = hashes
}
```

Overall: it's good idea to use raw.github - because it's already supporting "branches" concept (on R2 we likely need play with folders).

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]
- `init` is likely bad for it - because then all tests will also go to internet 
- need make `branch` configurable (or base-url configurable - with branch name in it)
- need some way/flag/env to disable it (maybe `dbg.EnvString` for MVP)
- this feels very easy to set empty value (on some http codes, or other corner cases) - probably need protection from empty set
```
 err == nil {
	BorMainnet = hashes
}
```

Overall: it's good idea to use raw.github - because it's already supporting "branches" concept (on R2 we likely need play with folders).

**Comment by Giulio2002** [comment]
Let's keep this open for when E35 will be released. will do those changes too

**Comment by Giulio2002** [comment]
```
func fetchSnapshotHashes(url string) ([]byte, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	res, err := io.ReadAll(resp.Body)
	if len(res) == 0 {
		return nil, fmt.Errorf("empty response from %s", url)
	}
	return res, err
}

```

Btw we already treat empty response as error if their length is 0

**Comment by Giulio2002** [comment]
oh wait need to resolve comments

**Comment by AskAlexSharov** [comment]
added `SNAPS_GIT_BRANCH` for re-defining

**Pull request merged**
